const groups = [
  {id:"essentials",title:"Premiers mots",emoji:"✨",words:[
    ["hello","bonjour / salut","Hello! How are you? · Salut ! Comment vas-tu ?"],["please","s’il te plaît / s’il vous plaît","A tea, please. · Un thé, s’il vous plaît."],["thank you","merci","Thank you for your help. · Merci pour ton aide."],["sorry","désolé(e) / pardon","Sorry, I’m late. · Désolé, je suis en retard."],["excuse me","excusez-moi / pardon","Excuse me, where is the station? · Excusez-moi, où est la gare ?"],["of course","bien sûr","Of course you can come. · Bien sûr, tu peux venir."],["maybe","peut-être","Maybe we can go tomorrow. · Peut-être qu’on peut y aller demain."],["actually","en fait / à vrai dire","Actually, I prefer tea. · En fait, je préfère le thé."],["usually","d’habitude / généralement","I usually walk to work. · D’habitude, je vais au travail à pied."],["enough","assez","We have enough time. · Nous avons assez de temps."],["almost","presque","It’s almost ready. · C’est presque prêt."],["together","ensemble","Let’s do it together. · Faisons-le ensemble."],["someone","quelqu’un","Someone is at the door. · Il y a quelqu’un à la porte."],["something","quelque chose","I need something to drink. · J’ai besoin de quelque chose à boire."],["anyway","de toute façon","Anyway, let’s start. · De toute façon, commençons."]]},
  {id:"daily",title:"Vie quotidienne",emoji:"🏠",words:[
    ["wake up","se réveiller","I wake up at seven. · Je me réveille à sept heures."],["get dressed","s’habiller","She gets dressed quickly. · Elle s’habille vite."],["leave","partir / quitter","We leave home at eight. · Nous partons de la maison à huit heures."],["arrive","arriver","What time do you arrive? · À quelle heure arrives-tu ?"],["come back","revenir / rentrer","I come back after work. · Je rentre après le travail."],["tidy up","ranger","Please tidy up your room. · Range ta chambre, s’il te plaît."],["borrow","emprunter","Can I borrow your pen? · Est-ce que je peux t’emprunter ton stylo ?"],["lend","prêter","Could you lend me a book? · Pourrais-tu me prêter un livre ?"],["need","avoir besoin de","I need a little help. · J’ai besoin d’un peu d’aide."],["choose","choisir","Choose the colour you like. · Choisis la couleur qui te plaît."],["remember","se souvenir / se rappeler","Remember to call your mum. · Pense à appeler ta mère."],["forget","oublier","Don’t forget your keys. · N’oublie pas tes clés."],["busy","occupé(e) / débordé(e)","I’m busy this afternoon. · Je suis occupé cet après-midi."],["quiet","calme / silencieux","It’s quiet in here. · C’est calme ici."],["comfortable","confortable / à l’aise","These shoes are comfortable. · Ces chaussures sont confortables."]]},
  {id:"travel",title:"Voyage & directions",emoji:"🧭",words:[
    ["ticket","billet","I’d like a return ticket. · Je voudrais un billet aller-retour."],["platform","quai","The train leaves from platform four. · Le train part du quai quatre."],["luggage","bagages","Where can I leave my luggage? · Où puis-je laisser mes bagages ?"],["entrance","entrée","The entrance is around the corner. · L’entrée est au coin de la rue."],["straight ahead","tout droit","Go straight ahead for two minutes. · Continue tout droit pendant deux minutes."],["turn left","tourner à gauche","Turn left at the traffic lights. · Tourne à gauche au feu."],["nearby","à proximité / tout près","Is there a pharmacy nearby? · Y a-t-il une pharmacie à proximité ?"],["address","adresse","Could you write down the address? · Pourriez-vous noter l’adresse ?"],["miss","rater / manquer","I missed the bus. · J’ai raté le bus."],["journey","trajet / voyage","How was your journey? · Comment s’est passé ton trajet ?"],["book","réserver","I’d like to book a room. · Je voudrais réserver une chambre."],["abroad","à l’étranger","She lives abroad. · Elle vit à l’étranger."],["across from","en face de","The café is across from the museum. · Le café est en face du musée."],["behind","derrière","The car park is behind the hotel. · Le parking est derrière l’hôtel."],["available","disponible","Is this seat available? · Cette place est-elle libre ?"]]},
  {id:"food",title:"Repas & courses",emoji:"🍓",words:[
    ["meal","repas","We have our evening meal at seven. · Nous dînons à sept heures."],["hungry","avoir faim","I’m getting hungry. · Je commence à avoir faim."],["thirsty","avoir soif","Would you like some water? I’m thirsty. · Tu voudrais de l’eau ? J’ai soif."],["bill","addition / facture","Could we have the bill, please? · L’addition, s’il vous plaît."],["tap water","eau du robinet","Could I have tap water? · Puis-je avoir de l’eau du robinet ?"],["order","commander","Are you ready to order? · Vous êtes prêts à commander ?"],["delicious","délicieux / délicieuse","This soup is delicious. · Cette soupe est délicieuse."],["spicy","épicé","Is this dish very spicy? · Ce plat est-il très épicé ?"],["ingredients","ingrédients","What are the ingredients? · Quels sont les ingrédients ?"],["allergy","allergie","I have a nut allergy. · Je suis allergique aux fruits à coque."],["receipt","ticket de caisse / reçu","Keep the receipt. · Garde le ticket de caisse."],["ripe","mûr(e)","These peaches are ripe. · Ces pêches sont mûres."]] },
  {id:"feelings",title:"Personnes & émotions",emoji:"💛",words:[
    ["excited","enthousiaste / impatient(e)","I’m excited about the trip. · Le voyage me rend enthousiaste."],["worried","inquiet / inquiète","Don’t be worried. · Ne t’inquiète pas."],["proud","fier / fière","I’m proud of you. · Je suis fier de toi."],["kind","gentil / bienveillant","That was very kind of you. · C’était très gentil de ta part."],["shy","timide","He’s a little shy. · Il est un peu timide."],["afraid","avoir peur","She’s afraid of spiders. · Elle a peur des araignées."],["miss","manquer à quelqu’un","I miss my friends. · Mes amis me manquent."],["feel","se sentir / ressentir","How are you feeling today? · Comment te sens-tu aujourd’hui ?"],["hope","espérer","I hope you feel better soon. · J’espère que tu iras bientôt mieux."],["trust","faire confiance","You can trust me. · Tu peux me faire confiance."],["lonely","seul / esseulé","He felt lonely in the new city. · Il se sentait seul dans cette nouvelle ville."],["upset","contrarié / triste","She was upset about the result. · Le résultat l’a contrariée."]]},
  {id:"study",title:"Études & travail",emoji:"📚",words:[
    ["improve","s’améliorer / améliorer","Your English is improving. · Ton anglais s’améliore."],["explain","expliquer","Can you explain this rule? · Peux-tu expliquer cette règle ?"],["understand","comprendre","I understand the question. · Je comprends la question."],["mistake","erreur","Making mistakes is part of learning. · Faire des erreurs fait partie de l’apprentissage."],["although","bien que / même si","Although it was late, we kept talking. · Même s’il était tard, nous avons continué à parler."],["instead","à la place","Let’s walk instead. · Allons-y à pied à la place."],["both","les deux","Both answers are correct. · Les deux réponses sont correctes."],["either","l’un ou l’autre / non plus","You can choose either option. · Tu peux choisir l’une ou l’autre option."],["during","pendant / au cours de","No phones during the lesson. · Pas de téléphone pendant le cours."],["deadline","date limite","The deadline is Friday. · La date limite est vendredi."],["skill","compétence","Listening is an important skill. · L’écoute est une compétence importante."],["immediately","immédiatement / tout de suite","Please call me immediately. · Appelle-moi tout de suite, s’il te plaît."]]},
  {id:"connectors",title:"Petits mots puissants",emoji:"🔗",words:[
    ["already","déjà","I’ve already eaten. · J’ai déjà mangé."],["yet","déjà / encore","Have you finished yet? · As-tu déjà terminé ?"],["still","encore / toujours","Are you still here? · Es-tu encore là ?"],["just","venir de / juste","I’ve just arrived. · Je viens d’arriver."],["ever","déjà (dans une question)","Have you ever tried sushi? · As-tu déjà goûté les sushis ?"],["since","depuis (point de départ)","I’ve lived here since 2020. · J’habite ici depuis 2020."],["for","depuis / pendant (durée)","We’ve waited for an hour. · Nous attendons depuis une heure."],["unless","à moins que / sauf si","You won’t pass unless you practise. · Tu ne réussiras pas si tu ne t’entraînes pas."],["however","cependant / toutefois","It’s expensive. However, it’s very good. · C’est cher. Cependant, c’est très bon."],["therefore","donc / par conséquent","It was raining; therefore, we stayed home. · Il pleuvait, donc nous sommes restés à la maison."],["instead of","au lieu de","Walk instead of taking the car. · Marche au lieu de prendre la voiture."],["as soon as","dès que","Call me as soon as you arrive. · Appelle-moi dès que tu arrives."]]},
  {id:"everyday",title:"Temps & quotidien",emoji:"🗓️",words:[
    ["yesterday","hier","I saw her yesterday. · Je l’ai vue hier."],["tomorrow","demain","We’re leaving tomorrow. · Nous partons demain."],["last week","la semaine dernière","I was ill last week. · J’étais malade la semaine dernière."],["next month","le mois prochain","They’re moving next month. · Ils déménagent le mois prochain."],["early","tôt / en avance","We arrived early. · Nous sommes arrivés en avance."],["late","tard / en retard","Sorry I’m late. · Désolé, je suis en retard."],["often","souvent","How often do you exercise? · À quelle fréquence fais-tu du sport ?"],["rarely","rarement","He rarely watches TV. · Il regarde rarement la télé."],["once","une fois","I’ve been there once. · J’y suis allé une fois."],["twice","deux fois","She called me twice. · Elle m’a appelé deux fois."],["at the moment","en ce moment","I’m studying at the moment. · J’étudie en ce moment."],["in a hurry","pressé(e)","I’m in a hurry. · Je suis pressé."]]}
];
const words = groups.flatMap(g=>g.words.map(w=>{const legacyId=w[0].toLowerCase().replace(/[^a-z0-9]+/g,"-");return{id:g.id+"-"+legacyId,legacyId,en:w[0],fr:w[1],example:w[2],topic:g.id,topicName:g.title}}));

const grammar = [
  {id:"present-simple",topic:"Présent",level:"Débutant",name:"Présent simple · Present simple",lead:"Une habitude, un fait général ou une chose qui est vraie en général.",form:"Sujet + verbe de base (he / she / it : souvent + s)",examples:[["I walk to school every day.","Je vais à l’école à pied tous les jours."],["She works in a hospital.","Elle travaille dans un hôpital."],["Water boils at 100°C.","L’eau bout à 100 °C."]],uses:["Habitudes et routines : souvent avec always, usually, often, every day.","Faits et vérités générales.","Horaires officiels : The train leaves at six."],trap:"À he / she / it, pense au -s : She likes, he goes. Pour une question, le -s revient sur does : Does she like…?",memory:"Imagine le présent simple comme une horloge qui tourne : les choses reviennent, encore et encore."},
  {id:"present-continuous",topic:"Présent",level:"Débutant",name:"Présent en -ing · Present continuous",lead:"Une action en cours maintenant, une situation temporaire ou un arrangement futur déjà prévu.",form:"am / is / are + verbe-ing",examples:[["I’m reading right now.","Je suis en train de lire."],["She’s staying with us this week.","Elle loge chez nous cette semaine."],["We’re meeting Sam at six.","Nous retrouvons Sam à six heures."]],uses:["Action qui se passe au moment où on parle.","Situation temporaire, même si elle ne se déroule pas pile maintenant.","Projet futur organisé : I’m flying on Monday."],trap:"Les verbes d’état comme know, want et believe sont généralement au simple, pas en -ing : I know the answer.",memory:"Une petite vidéo en direct : l’action est encore en train de se dérouler."},
  {id:"past-simple",topic:"Passé",level:"Débutant",name:"Prétérit · Past simple",lead:"Une action ou une période terminée dans le passé, souvent située à un moment précis.",form:"Verbe régulier + -ed · ou 2ᵉ forme irrégulière",examples:[["We visited London last year.","Nous avons visité Londres l’an dernier."],["He went home at ten.","Il est rentré chez lui à dix heures."],["Did you see the match?","As-tu vu le match ?"]],uses:["Action finie : yesterday, last week, in 2022, two days ago.","Suite d’actions dans un récit.","Négation et question : did + base verbale (didn’t go, did you go?)."],trap:"Après did / didn’t, le verbe reste à la base : Did you go? (pas Did you went?).",memory:"Le prétérit met un point final sur la ligne du temps : c’est fini."},
  {id:"past-continuous",topic:"Passé",level:"Intermédiaire",name:"Passé en -ing · Past continuous",lead:"Une action était en cours à un moment passé, souvent interrompue par une autre action.",form:"was / were + verbe-ing",examples:[["I was cooking when you called.","Je cuisinais quand tu as appelé."],["They were sleeping at midnight.","Ils dormaient à minuit."],["While she was driving, it started to snow.","Pendant qu’elle conduisait, il a commencé à neiger."]],uses:["Décor ou action en cours dans un récit.","Action longue interrompue par une action plus courte au prétérit.","Deux actions qui se déroulent en même temps : while I was reading, he was cooking."],trap:"L’action qui coupe la scène est souvent au past simple : I was walking when it began to rain.",memory:"Imagine une scène en pause : le décor continue, puis un événement y entre."},
  {id:"present-perfect",topic:"Présent",level:"Intermédiaire",name:"Present perfect",lead:"Un lien entre un événement passé et maintenant : expérience, période pas finie ou résultat visible aujourd’hui.",form:"have / has + participe passé (3ᵉ forme)",examples:[["I’ve lost my keys.","J’ai perdu mes clés (je ne les ai toujours pas)."],["Have you ever been to Rome?","Es-tu déjà allé à Rome ?"],["She’s worked here since May.","Elle travaille ici depuis mai."]],uses:["Expérience de vie sans préciser quand : ever, never.","Période qui continue : today, this week, so far.","Résultat présent; avec for (durée) et since (départ)."],trap:"Avec un moment passé terminé (yesterday, in 2019), utilise plutôt le past simple : I saw him yesterday.",memory:"Une passerelle relie le passé à maintenant : l’événement est derrière, son lien est encore là."},
  {id:"present-perfect-continuous",topic:"Présent",level:"Avancé",name:"Present perfect continuous",lead:"Met l’accent sur une activité qui a commencé avant maintenant et qui continue, ou dont on voit l’effet.",form:"have / has + been + verbe-ing",examples:[["I’ve been learning English for a year.","J’apprends l’anglais depuis un an."],["She’s been running; she’s out of breath.","Elle a couru / court depuis un moment; elle est essoufflée."],["How long have you been waiting?","Depuis combien de temps attends-tu ?"]],uses:["Durée d’une action : souvent for, since, all morning.","Activité récente dont le résultat se voit maintenant.","Met l’accent sur le déroulement plutôt que sur le résultat achevé."],trap:"Compare : I’ve painted the room (résultat) / I’ve been painting the room (activité, peut-être pas finie). Certains verbes d’état ne prennent pas -ing.",memory:"La passerelle est encore animée : on voit les traces d’une activité en mouvement."},
  {id:"past-perfect",topic:"Passé",level:"Avancé",name:"Plus-que-parfait · Past perfect",lead:"Une action s’est produite avant une autre action passée. C’est le passé du passé.",form:"had + participe passé",examples:[["The film had started when we arrived.","Le film avait commencé quand nous sommes arrivés."],["She was tired because she hadn’t slept.","Elle était fatiguée parce qu’elle n’avait pas dormi."],["Had you met him before the party?","L’avais-tu rencontré avant la fête ?"]],uses:["Clarifier l’ordre de deux événements passés.","Expliquer une situation passée par une action encore plus ancienne.","Négation : hadn’t + participe passé; question : Had …?"],trap:"Ne l’emploie pas automatiquement pour toute phrase au passé; il sert surtout quand l’ordre mérite d’être rendu clair.",memory:"Deux points sont dans le passé : le past perfect est le plus ancien, avant le second."},
  {id:"past-perfect-continuous",topic:"Passé",level:"Avancé",name:"Past perfect continuous",lead:"Met l’accent sur la durée d’une activité qui se déroulait avant un moment passé.",form:"had + been + verbe-ing",examples:[["We had been walking for hours before we found the hotel.","Nous marchions depuis des heures avant de trouver l’hôtel."],["He was tired because he’d been working all night.","Il était fatigué parce qu’il avait travaillé toute la nuit."]],uses:["Durée antérieure à un repère passé.","Cause ou activité en cours avant un résultat passé.","Souvent avec for / since et un second événement au passé."],trap:"Past perfect simple regarde davantage le résultat / le fait accompli; continuous souligne la durée ou l’activité.",memory:"Retourne sur la ligne du temps : une action longue s’étire avant le repère passé."},
  {id:"will",topic:"Futur",level:"Débutant",name:"Futur avec will",lead:"Une décision prise sur le moment, une promesse, une offre ou une prédiction personnelle.",form:"will + verbe de base (forme courte : ’ll)",examples:[["I’ll answer the phone.","Je vais répondre au téléphone (décision prise maintenant)."],["I’ll help you.","Je vais t’aider / Je t’aiderai."],["I think it will rain.","Je pense qu’il va pleuvoir."]],uses:["Décision spontanée et offre : I’ll carry that for you.","Promesse : I’ll call you tonight.","Prédiction ou opinion : I think they’ll win."],trap:"Après will, garde le verbe à la base, sans to et sans -s : she will come.",memory:"Will est le bouton décision / promesse que tu actionnes maintenant."},
  {id:"going-to",topic:"Futur",level:"Débutant",name:"Futur avec going to",lead:"Un projet déjà décidé ou une prédiction fondée sur un indice présent.",form:"am / is / are + going to + verbe de base",examples:[["We’re going to move next month.","Nous allons déménager le mois prochain."],["Look at those clouds! It’s going to rain.","Regarde ces nuages ! Il va pleuvoir."],["What are you going to do?","Qu’est-ce que tu vas faire ?"]],uses:["Intention ou plan déjà en tête.","Prédiction appuyée par ce qu’on voit maintenant.","Forme très courante à l’oral, souvent gonna dans la parole informelle."],trap:"Compare avec will : will peut être spontané; going to présente un plan ou un signe déjà là.",memory:"Le plan est déjà dans ton sac, ou l’indice est juste devant toi."},
  {id:"present-future",topic:"Futur",level:"Intermédiaire",name:"Présent pour parler du futur",lead:"Le présent peut exprimer un horaire fixe ou un arrangement déjà organisé.",form:"Present simple = horaires · am/is/are + -ing = arrangement",examples:[["The train leaves at 8:15.","Le train part à 8 h 15 (horaire)."],["I’m seeing the dentist tomorrow.","Je vois le dentiste demain (rendez-vous prévu)."],["The shop opens at nine.","Le magasin ouvre à neuf heures."]],uses:["Present simple pour programmes, horaires, calendriers officiels.","Present continuous pour rendez-vous et arrangements concrets.","La date ou l’heure future apparaît souvent dans la phrase."],trap:"On ne choisit pas une forme seulement grâce à tomorrow : c’est le sens (horaire, arrangement, intention) qui guide.",memory:"Un horaire imprimé est fixe; un rendez-vous est déjà inscrit dans ton agenda."},
  {id:"future-continuous",topic:"Futur",level:"Avancé",name:"Future continuous",lead:"Une action sera en cours à un moment précis du futur.",form:"will + be + verbe-ing",examples:[["This time tomorrow, I’ll be flying to Paris.","Demain à la même heure, je serai en train de voler vers Paris."],["Will you be using the car tonight?","Est-ce que tu utiliseras la voiture ce soir ?"]],uses:["Action en cours à un repère futur.","Question polie sur ce qui est prévu : Will you be staying long?"],trap:"Le focus est sur ce qui sera en cours, pas sur une simple décision future.",memory:"Place une petite fenêtre sur le futur : l’action défile à l’intérieur."},
  {id:"future-perfect",topic:"Futur",level:"Avancé",name:"Future perfect",lead:"Une action sera terminée avant un repère du futur.",form:"will + have + participe passé",examples:[["I’ll have finished by Friday.","J’aurai terminé d’ici vendredi."],["By next year, they’ll have built the bridge.","D’ici l’année prochaine, ils auront construit le pont."]],uses:["Action achevée avant un moment futur.","Repère fréquent : by Friday, by then, by the time …"],trap:"By signifie ici « au plus tard d’ici ». Ne confonds pas avec until (« jusqu’à »).",memory:"La ligne du temps avance jusqu’à vendredi : l’action sera déjà cochée."},
  {id:"zero-conditional",topic:"Conditionnels",level:"Intermédiaire",name:"Conditionnel zéro · Zero conditional",lead:"Une règle, un fait général ou une conséquence qui se produit normalement.",form:"If + présent simple, présent simple",examples:[["If you heat ice, it melts.","Si on chauffe de la glace, elle fond."],["If I’m tired, I go to bed early.","Quand je suis fatigué, je me couche tôt."]],uses:["Lois, résultats prévisibles, habitudes.","If peut souvent se traduire par « si » ou « quand » selon le contexte."],trap:"Les deux morceaux sont au présent; ce n’est pas un futur.",memory:"Un domino : chaque fois que la condition arrive, la même suite se produit."},
  {id:"first-conditional",topic:"Conditionnels",level:"Intermédiaire",name:"Premier conditionnel · First conditional",lead:"Une condition réelle ou possible et son résultat probable dans le futur.",form:"If + présent simple, will + verbe",examples:[["If it rains, we’ll stay home.","S’il pleut, nous resterons à la maison."],["If you study, you’ll understand it.","Si tu étudies, tu comprendras."]],uses:["Situation future ouverte / possible.","On peut utiliser un impératif ou un modal dans la proposition résultat : If you see Anna, tell her."],trap:"Dans la proposition en if, on met normalement le présent, pas will : If it rains…",memory:"La branche est possible : si elle s’allume, le futur suit."},
  {id:"second-conditional",topic:"Conditionnels",level:"Intermédiaire",name:"Deuxième conditionnel · Second conditional",lead:"Une situation imaginaire, hypothétique ou peu probable maintenant ou dans le futur.",form:"If + prétérit, would + verbe",examples:[["If I had more time, I would travel.","Si j’avais plus de temps, je voyagerais."],["If I were you, I’d ask for help.","À ta place, je demanderais de l’aide."]],uses:["Scénarios imaginaires ou conseils.","Were est traditionnellement utilisé avec tous les sujets dans If I were you; was s’entend aussi dans la langue courante."],trap:"Le prétérit indique ici la distance avec la réalité, pas nécessairement le passé.",memory:"On ouvre une porte imaginaire : on explore ce qu’il y aurait de l’autre côté."},
  {id:"third-conditional",topic:"Conditionnels",level:"Avancé",name:"Troisième conditionnel · Third conditional",lead:"On imagine un passé différent et un résultat passé qui n’a pas eu lieu.",form:"If + past perfect, would have + participe passé",examples:[["If we had left earlier, we would have caught the train.","Si nous étions partis plus tôt, nous aurions attrapé le train."],["She would have passed if she had revised.","Elle aurait réussi si elle avait révisé."]],uses:["Regret, reproche ou hypothèse sur une occasion passée.","Les deux parties parlent d’événements qui ne se sont pas produits."],trap:"Après if, utilise had + participe passé; évite would dans la partie condition.",memory:"Un retour impossible dans le temps : tu dessines une autre fin, mais tu sais que la vraie histoire est passée."},
  {id:"modals",topic:"Construire ses phrases",level:"Intermédiaire",name:"Modaux · can, could, must, should…",lead:"Les modaux ajoutent la capacité, la possibilité, l’obligation, le conseil ou la permission.",form:"Modal + verbe de base (sans to, sans -s)",examples:[["I can swim.","Je sais nager / Je peux nager."],["You should rest.","Tu devrais te reposer."],["You must wear a seat belt.","Tu dois porter une ceinture."],["It might rain.","Il se pourrait qu’il pleuve."]],uses:["can / could : capacité, permission ou possibilité; could rend souvent la demande plus polie.","should : conseil; must : obligation forte; might / may : possibilité.","mustn’t = interdit; don’t have to = pas obligé : le sens change."],trap:"Pas de to après la plupart des modaux : can go. Exception à apprendre : have to n’est pas un modal pur.",memory:"Chaque modal est un petit filtre qui colore le verbe : possible, conseillé, obligatoire…"},
  {id:"passive",topic:"Construire ses phrases",level:"Avancé",name:"Voix passive · Passive voice",lead:"On met l’accent sur ce qui subit l’action ou sur le résultat, plutôt que sur la personne qui agit.",form:"be (au temps voulu) + participe passé",examples:[["The cake was made by my dad.","Le gâteau a été fait par mon père."],["English is spoken here.","On parle anglais ici."],["The road is being repaired.","La route est en train d’être réparée."]],uses:["L’auteur de l’action est inconnu ou peu important.","Style informatif : The building was built in 1900.","On peut nommer l’auteur avec by si nécessaire."],trap:"Le temps est porté par be; le verbe principal reste au participe passé.",memory:"La caméra filme l’objet qui reçoit l’action, pas la personne qui la fait."},
  {id:"questions",topic:"Construire ses phrases",level:"Débutant",name:"Poser des questions",lead:"L’anglais a besoin d’un auxiliaire pour construire la plupart des questions oui / non.",form:"Mot interrogatif + auxiliaire + sujet + verbe ?",examples:[["Do you like music?","Est-ce que tu aimes la musique ?"],["Where does she live?","Où habite-t-elle ?"],["Did they call you?","T’ont-ils appelé ?"],["Are you ready?","Es-tu prêt ?"]],uses:["Présent simple : do / does; prétérit : did.","Avec be ou un modal, inverse : Are you…? Can she…?", "Mot interrogatif fréquent : who, what, where, when, why, how."],trap:"Avec does ou did, le verbe perd la marque : Does he work? Did he work?",memory:"L’auxiliaire fait le premier pas et vient se placer devant le sujet."},
  {id:"articles",topic:"Construire ses phrases",level:"Intermédiaire",name:"Articles · a, an, the ou rien ?",lead:"L’article dépend surtout de la façon dont on présente le nom : un exemplaire, quelque chose d’identifié, ou une idée générale.",form:"a / an = un parmi d’autres · the = celui/celle identifié(e)",examples:[["I saw a dog. The dog was tiny.","J’ai vu un chien. Le chien était minuscule."],["She’s an engineer.","Elle est ingénieure."],["I love music.","J’aime la musique (en général)."]],uses:["a devant un son consonne; an devant un son voyelle : a university, an hour.","the si la personne sait de quoi on parle ou si le nom est unique dans le contexte.","Pas d’article devant beaucoup de pluriels et d’idées générales : Cats are curious."],trap:"Le choix entre a / an dépend du son, pas seulement de la première lettre.",memory:"Première fois : un / une. Deuxième fois, on sait lequel : le / la."},
  {id:"word-order",topic:"Construire ses phrases",level:"Débutant",name:"Ordre des mots",lead:"L’ordre sujet–verbe–complément est souvent plus fixe qu’en français.",form:"Sujet + verbe + objet + lieu + temps (ordre fréquent)",examples:[["She bought a book in town yesterday.","Elle a acheté un livre en ville hier."],["I really like it.","Je l’aime vraiment bien."],["He doesn’t speak French.","Il ne parle pas français."]],uses:["La phrase affirmative commence généralement par son sujet.","L’adverbe de fréquence se place souvent avant le verbe principal : I often read; après be : She is often late.","Les adjectifs précèdent normalement le nom : a beautiful house."],trap:"Évite de calquer chaque mot sur le français; les pronoms objets se placent avant / après le verbe selon sa construction.",memory:"Aligne les wagons : qui fait quoi, à qui, où, quand."},
  {id:"prepositions",topic:"Construire ses phrases",level:"Intermédiaire",name:"Prépositions de temps · at, on, in",lead:"Un repère simple : at pour un point, on pour un jour, in pour une période plus large.",form:"AT l’heure · ON le jour / la date · IN le mois / l’année / une période",examples:[["at six o’clock · at night","à six heures · la nuit"],["on Monday · on 12 May","lundi · le 12 mai"],["in July · in 2026 · in the morning","en juillet · en 2026 · le matin"]],uses:["at : moment précis, at noon, at the weekend (anglais britannique courant).", "on : jour ou date; on my birthday.","in : mois, année, saison, période de la journée."],trap:"On dit at night, mais in the morning / afternoon / evening. Les prépositions peuvent varier selon les expressions figées.",memory:"Zoom : point minuscule (at), case du calendrier (on), grande période (in)."},
  {id:"reported-speech",topic:"Construire ses phrases",level:"Avancé",name:"Discours rapporté · Reported speech",lead:"On rapporte ce que quelqu’un a dit sans forcément reprendre ses mots exacts.",form:"say / tell + proposition · le temps recule souvent après un verbe au passé",examples:[["“I’m tired.” → She said (that) she was tired.","« Je suis fatiguée. » → Elle a dit qu’elle était fatiguée."],["“We will call.” → They said they would call.","« Nous appellerons. » → Ils ont dit qu’ils appelleraient."],["“I like it.” → He told me (that) he liked it.","« J’aime ça. » → Il m’a dit qu’il aimait ça."]],uses:["Pronoms et repères de temps peuvent changer : today → that day; here → there.","tell prend souvent une personne : tell me; say n’en prend pas directement.","Le recul du temps est fréquent après said / told, mais dépend du contexte."],trap:"On dit tell me, mais say something to me; pas tell that sans destinataire dans cet usage.",memory:"Tu déplaces la caméra : les paroles sont maintenant racontées depuis un autre moment."}
];

const verbGroups=[
  {id:"core",title:"Les plus utilisés",verbs:[
    ["be","was / were","been","être"],["have","had","had","avoir"],["do","did","done","faire"],["say","said","said","dire"],["go","went","gone","aller"],["get","got","got / gotten","obtenir, devenir"],["make","made","made","faire, fabriquer"],["know","knew","known","savoir, connaître"],["think","thought","thought","penser"],["take","took","taken","prendre"],["see","saw","seen","voir"],["come","came","come","venir"],["give","gave","given","donner"],["find","found","found","trouver"],["tell","told","told","dire, raconter"],["become","became","become","devenir"],["leave","left","left","partir, laisser"],["feel","felt","felt","ressentir"],["put","put","put","mettre"],["bring","brought","brought","apporter"],["begin","began","begun","commencer"],["keep","kept","kept","garder"],["hold","held","held","tenir"],["write","wrote","written","écrire"],["stand","stood","stood","être debout"],["hear","heard","heard","entendre"],["let","let","let","laisser, permettre"],["mean","meant","meant","signifier"],["set","set","set","poser, fixer"],["meet","met","met","rencontrer"]]},
  {id:"same",title:"Les trois formes identiques",verbs:[["cut","cut","cut","couper"],["put","put","put","mettre"],["hit","hit","hit","frapper"],["let","let","let","laisser, permettre"],["cost","cost","cost","coûter"],["hurt","hurt","hurt","faire mal"],["shut","shut","shut","fermer"],["read","read","read","lire (prononciation passée : /red/)"]] },
  {id:"vowel",title:"i – a – u",verbs:[["sing","sang","sung","chanter"],["drink","drank","drunk","boire"],["swim","swam","swum","nager"],["ring","rang","rung","sonner"],["begin","began","begun","commencer"],["sink","sank","sunk","couler"],["spring","sprang","sprung","bondir"]]},
  {id:"ought",title:"La famille -ought / -aught",verbs:[["buy","bought","bought","acheter"],["bring","brought","brought","apporter"],["think","thought","thought","penser"],["fight","fought","fought","se battre"],["catch","caught","caught","attraper"],["teach","taught","taught","enseigner"]]},
  {id:"other",title:"À apprendre aussi",verbs:[["eat","ate","eaten","manger"],["fall","fell","fallen","tomber"],["fly","flew","flown","voler"],["forget","forgot","forgotten","oublier"],["grow","grew","grown","grandir, pousser"],["run","ran","run","courir"],["speak","spoke","spoken","parler"],["choose","chose","chosen","choisir"],["break","broke","broken","casser"],["drive","drove","driven","conduire"],["wear","wore","worn","porter (un vêtement)"],["win","won","won","gagner"],["lose","lost","lost","perdre"],["send","sent","sent","envoyer"],["build","built","built","construire"],["sleep","slept","slept","dormir"],["sell","sold","sold","vendre"],["pay","paid","paid","payer"],["sit","sat","sat","s’asseoir"],["understand","understood","understood","comprendre"],["rise","rose","risen","se lever, augmenter"],["throw","threw","thrown","lancer"],["show","showed","shown","montrer"],["hide","hid","hidden","cacher"],["break","broke","broken","casser"],["draw","drew","drawn","dessiner"],["fall","fell","fallen","tomber"],["wear","wore","worn","porter"],["feed","fed","fed","nourrir"],["lead","led","led","mener"],["shine","shone","shone","briller"],["stick","stuck","stuck","coller, rester"]]}
].map(g=>({...g,verbs:g.verbs.map(v=>({base:v[0],past:v[1],part:v[2],fr:v[3]}))}));
const verbs=verbGroups.flatMap(g=>g.verbs.map(v=>({...v,group:g.id,groupName:g.title})));

const phraseGroups=[
  {id:"polite",title:"Dire bonjour et rester poli",items:[["Nice to meet you.","Enchanté(e) de faire ta connaissance.","Se présenter à quelqu’un pour la première fois."],["How’s it going?","Comment ça va ?","Formule familière; une réponse courte suffit."],["Thanks, I really appreciate it.","Merci, j’apprécie vraiment.","Pour remercier chaleureusement."],["Would you mind helping me?","Cela vous dérangerait de m’aider ?","Demande polie; mind est suivi de -ing."],["Sorry, I didn’t catch that.","Désolé, je n’ai pas compris / entendu.","Pour demander de répéter sans dire “What?” sèchement."],["Could you say that again, please?","Pourriez-vous répéter, s’il vous plaît ?","Demander une répétition de façon polie."]] },
  {id:"conversation",title:"Faire vivre une conversation",items:[["What do you think?","Qu’est-ce que tu en penses ?","Demander l’avis de l’autre."],["I’m not sure, but…","Je ne suis pas sûr(e), mais…","Donner une réponse nuancée."],["That makes sense.","C’est logique / je comprends.","Montrer qu’on suit le raisonnement."],["It depends.","Ça dépend.","Garder la réponse ouverte."],["By the way…","Au fait…","Introduire un nouveau sujet."],["I see what you mean.","Je vois ce que tu veux dire.","Montrer qu’on a compris le point de vue."]] },
  {id:"travel",title:"Voyager & demander son chemin",items:[["How do I get to the station?","Comment aller à la gare ?","Demander un itinéraire."],["Is this the right platform?","C’est le bon quai ?","Vérifier avant de monter dans le train."],["Could you show me on the map?","Pourriez-vous me montrer sur la carte ?","Une façon simple de clarifier un itinéraire."],["I have a reservation under Martin.","J’ai une réservation au nom de Martin.","À l’hôtel ou au restaurant."],["How much is a return ticket?","Combien coûte un billet aller-retour ?","Acheter un billet de transport."]] },
  {id:"food",title:"Au café ou au restaurant",items:[["Could I see the menu, please?","Puis-je voir le menu, s’il vous plaît ?","Demander le menu."],["I’d like the soup, please.","Je voudrais la soupe, s’il vous plaît.","I’d like est poli et naturel pour commander."],["Does this contain nuts?","Est-ce que cela contient des fruits à coque ?","Vérifier un ingrédient; préciser son allergie si besoin."],["Could we have the bill, please?","L’addition, s’il vous plaît ?","Formule courante pour demander l’addition."],["Tap water is fine, thank you.","L’eau du robinet me convient, merci.","Répondre quand on demande quelle eau on souhaite. "]] },
  {id:"study",title:"En classe ou au travail",items:[["I have a question.","J’ai une question.","Prendre la parole simplement."],["Could you explain this part?","Pourriez-vous expliquer cette partie ?","Demander une explication."],["I’ll get back to you this afternoon.","Je reviens vers vous cet après-midi.","Promettre une réponse plus tard."],["Let me check.","Laissez-moi vérifier.","Gagner un instant avant de répondre."],["I’m working on it.","Je m’en occupe / je travaille dessus.","Dire qu’une tâche est en cours."]] },
  {id:"help",title:"Quand on a besoin d’aide",items:[["Could you help me, please?","Pourriez-vous m’aider, s’il vous plaît ?","Demande directe et polie."],["I’m looking for this address.","Je cherche cette adresse.","Montrer une destination ou demander de l’aide."],["I don’t understand.","Je ne comprends pas.","On peut ajouter yet? « I don’t understand yet » = pas encore."],["Could you speak more slowly?","Pourriez-vous parler plus lentement ?","Demander de ralentir sans gêne."],["Where is the nearest pharmacy?","Où se trouve la pharmacie la plus proche ?","Demander un lieu à proximité."]] }
];

const sounds=[
  {symbol:"th",title:"Deux sons pour ‘th’",text:"La pointe de la langue se place légèrement entre les dents. L’air passe; la voix vibre pour le son de this, pas pour celui de think.",examples:"this · they · mother   /   think · three · both",hint:"N’ajoute pas un s : think commence par un son différent de sink."},
  {symbol:"h",title:"Le h qui laisse passer l’air",text:"Dans happy ou hotel, le h s’entend comme un souffle doux. La bouche commence à expirer avant la voyelle.",examples:"happy · hello · behind",hint:"Garde un petit souffle au début : le h n’est pas muet dans ces mots."},
  {symbol:"r",title:"Le r anglais",text:"Le r est généralement prononcé sans roulement de langue. L’accent et la position de la langue varient selon les régions.",examples:"red · around · very",hint:"Compare plusieurs accents : cherche une prononciation compréhensible, pas une imitation parfaite."},
  {symbol:"ə",title:"Le schwa · ə",text:"C’est une voyelle très courte et détendue dans les syllabes non accentuées. Elle ressemble parfois à un petit ‘e’ discret.",examples:"about · banana · teacher",hint:"Le rythme compte : les syllabes fortes ressortent, les autres deviennent souvent plus légères."},
  {symbol:"iː / ɪ",title:"Sheep ou ship ?",text:"Deux sons différents : le i long de sheep et le i bref de ship peuvent changer le mot.",examples:"sheep / ship · leave / live · seat / sit",hint:"Prononce les deux mots à voix haute; exagère un peu la longueur au début."},
  {symbol:"æ",title:"Le a de cat",text:"Dans de nombreux accents, cat contient une voyelle avant /ɛ/ et /ɑː/. L’ouverture de la bouche est utile à remarquer.",examples:"cat · map · black",hint:"Compare cat et cut : ce ne sont pas les mêmes voyelles."},
  {symbol:"-ed",title:"Trois façons de prononcer -ed",text:"La terminaison du prétérit régulier ne se prononce pas toujours pareil : /t/, /d/ ou /ɪd/.",examples:"worked → /t/ · played → /d/ · wanted → /ɪd/",hint:"Après le son /t/ ou /d/, ajoute une syllabe /ɪd/ : wanted, needed."},
  {symbol:"ˈ",title:"L’accent tonique",text:"Dans un mot de plusieurs syllabes, une syllabe ressort. La syllabe forte est marquée ici par ˈ juste avant.",examples:"TAble · aBOUT · imPORtant",hint:"Tape doucement le rythme en parlant; l’accent aide souvent plus que chaque lettre."}
];

const stateKey="anglais-sans-blocage-state-v1";
const studyDayLabels=[[1,"Lundi"],[2,"Mardi"],[3,"Mercredi"],[4,"Jeudi"],[5,"Vendredi"],[6,"Samedi"],[0,"Dimanche"]];
const validStudyDays=value=>{const days=Array.isArray(value)?[...new Set(value.filter(day=>Number.isInteger(day)&&day>=0&&day<=6))].sort((a,b)=>a-b):[];return days.length?days:[1,2,3,4,5]};
const themes=["clair","lavande","ocean","nuit"];
const freshState=()=>({knownWords:[],seenLessons:[],knownVerbs:[],savedPhrases:[],bestScore:null,lastVisit:null,streak:0,theme:"clair",studyDays:[1,2,3,4,5],reduceMotion:false});
const validIds=value=>Array.isArray(value)?[...new Set(value.filter(item=>typeof item==="string"))]:[];
let state=freshState();
try{
  const saved=JSON.parse(localStorage.getItem(stateKey)||"null");
  if(saved&&typeof saved==="object"&&!Array.isArray(saved))state={
    ...freshState(),
    knownWords:[...new Set(validIds(saved.knownWords).flatMap(id=>{const matches=words.filter(word=>word.legacyId===id).map(word=>word.id);return matches.length?matches:[id]}))],
    seenLessons:validIds(saved.seenLessons),
    knownVerbs:validIds(saved.knownVerbs),
    savedPhrases:validIds(saved.savedPhrases),
    bestScore:Number.isInteger(saved.bestScore)&&saved.bestScore>=0&&saved.bestScore<=10?saved.bestScore:null,
    lastVisit:typeof saved.lastVisit==="string"?saved.lastVisit:null,
    streak:Number.isInteger(saved.streak)&&saved.streak>=0?saved.streak:0,
    theme:themes.includes(saved.theme)?saved.theme:"clair",
    studyDays:validStudyDays(saved.studyDays),
    reduceMotion:saved.reduceMotion===true
  };
}catch{}
function persist(){try{localStorage.setItem(stateKey,JSON.stringify(state))}catch{toast("Le navigateur n’a pas pu enregistrer les progrès.")}}
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const ids=arr=>new Set(arr);
function toast(msg){const t=$("#toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2100)}
const viewNames={home:"Aujourd’hui",words:"Vocabulaire",grammar:"Grammaire & temps",verbs:"Verbes irréguliers",speak:"Phrases utiles",sounds:"Prononciation",quiz:"Quiz & défis",settings:"Réglages"};
function show(view){if(!viewNames[view])return;$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+view));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#crumb').textContent=viewNames[view];history.replaceState(null,"","#"+view);window.scrollTo({top:0,behavior:"smooth"});if(view==="words")renderWords();if(view==="grammar")renderGrammar();if(view==="verbs")renderVerbs();if(view==="speak")renderPhrases();if(view==="sounds")renderSounds();if(view==="quiz")renderQuiz();if(view==="settings")renderSettings();}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]'),go=e.target.closest('[data-go]');if(nav)show(nav.dataset.view);if(go)show(go.dataset.go);});

let wordIndex=0,wordShowAnswer=false,wordQuery="",wordTopic="all";
function initWordControls(){const select=$("#wordTopic");select.innerHTML='<option value="all">Toutes les catégories</option>'+groups.map(g=>`<option value="${g.id}">${g.emoji} ${esc(g.title)}</option>`).join("");select.addEventListener("change",()=>{wordTopic=select.value;wordIndex=0;wordShowAnswer=false;renderWords()});$("#wordSearch").addEventListener("input",e=>{wordQuery=e.target.value.trim().toLowerCase();wordIndex=0;wordShowAnswer=false;renderWords()})}
function filteredWords(){return words.filter(w=>(wordTopic==="all"||w.topic===wordTopic)&&(!wordQuery||`${w.en} ${w.fr} ${w.example}`.toLowerCase().includes(wordQuery)))}
function renderWords(){const list=filteredWords(),known=ids(state.knownWords);wordIndex=Math.max(0,Math.min(wordIndex,Math.max(0,list.length-1)));$("#wordsKnownBadge").textContent=`${known.size} mot${known.size===1?"":"s"} retenu${known.size===1?"":"s"}`;$("#wordListCount").textContent=`${list.length} mots`;const side=$("#wordList");if(!list.length){$("#flashcard").innerHTML='<div class="empty-state">Aucun mot ne correspond. Essaie une autre recherche.</div>';side.innerHTML="";return}const w=list[wordIndex];$("#flashcard").innerHTML=`<div class="flash-meta"><span>${esc(w.topicName)} · ${wordIndex+1} / ${list.length}</span><span>${known.has(w.id)?"✓ déjà retenu":"carte mémoire"}</span></div><div class="flash-en">${esc(w.en)}</div>${wordShowAnswer?`<div class="flash-fr">${esc(w.fr)}</div><div class="flash-example">${esc(w.example)}</div>`:`<div class="flash-ipa">Essaie de deviner avant de retourner la carte</div>`}<div class="flash-actions">${wordShowAnswer?`<button class="forget-button" id="markReview">À revoir</button><button class="remember-button" id="markKnown">Je le sais ✓</button>`:`<button class="remember-button" id="revealWord">Voir la réponse</button>`}<button class="soft-button" id="nextWord">Suivant →</button></div>`;side.innerHTML=list.map((x,i)=>`<button class="${i===wordIndex?"selected":""}" data-word-index="${i}"><span>${esc(x.en)}</span><span>${known.has(x.id)?'<b class="known-dot">✓</b>':esc(x.fr)}</span></button>`).join("");}
$("#wordList").addEventListener("click",e=>{const b=e.target.closest("[data-word-index]");if(b){wordIndex=Number(b.dataset.wordIndex);wordShowAnswer=false;renderWords()}});$("#flashcard").addEventListener("click",e=>{if(e.target.closest("#revealWord")){wordShowAnswer=true;renderWords()}if(e.target.closest("#nextWord")){wordIndex=(wordIndex+1)%filteredWords().length;wordShowAnswer=false;renderWords()}if(e.target.closest("#markKnown")){const w=filteredWords()[wordIndex];if(!state.knownWords.includes(w.id))state.knownWords.push(w.id);persist();wordIndex=(wordIndex+1)%filteredWords().length;wordShowAnswer=false;updateProgress();renderWords()}if(e.target.closest("#markReview")){wordIndex=(wordIndex+1)%filteredWords().length;wordShowAnswer=false;renderWords()}});

let grammarTopic="Présent",grammarId="present-simple";
function initGrammarTopics(){const topics=["Présent","Passé","Futur","Conditionnels","Construire ses phrases"];$("#grammarTopics").innerHTML=topics.map(t=>`<button class="${t===grammarTopic?"active":""}" data-grammar-topic="${esc(t)}">${esc(t)}</button>`).join("");$("#grammarTopics").addEventListener("click",e=>{const b=e.target.closest("[data-grammar-topic]");if(!b)return;grammarTopic=b.dataset.grammarTopic;grammarId=grammar.find(g=>g.topic===grammarTopic)?.id||grammarId;renderGrammar()});$("#grammarList").addEventListener("click",e=>{const b=e.target.closest("[data-grammar-id]");if(b){grammarId=b.dataset.grammarId;renderGrammar()}});$("#grammarDetail").addEventListener("click",e=>{if(e.target.closest("#lessonUnderstood")){if(!state.seenLessons.includes(grammarId))state.seenLessons.push(grammarId);persist();updateProgress();renderGrammar();toast("Leçon ajoutée à tes progrès ✓")}})}
function renderGrammar(){const set=grammar.filter(g=>g.topic===grammarTopic);if(!set.some(g=>g.id===grammarId))grammarId=set[0]?.id||grammar[0].id;$("#grammarTopics").innerHTML=[...new Set(grammar.map(g=>g.topic))].map(t=>`<button class="${t===grammarTopic?"active":""}" data-grammar-topic="${esc(t)}">${esc(t)}</button>`).join("");$("#grammarList").innerHTML=set.map(g=>`<button class="${g.id===grammarId?"active":""}" data-grammar-id="${g.id}"><span>${esc(g.level)}</span>${esc(g.name.split(" · ")[0])}</button>`).join("");const g=grammar.find(x=>x.id===grammarId);const done=state.seenLessons.includes(g.id);const placement=g.topic==="Passé"?"⟵ repère passé":g.topic==="Futur"?"repère futur ⟶":g.topic==="Présent"?"● maintenant":"repère";const marker=g.topic==="Futur"?"REPÈRE FUTUR":g.topic==="Passé"?"REPÈRE PASSÉ":"MAINTENANT";$("#grammarDetail").innerHTML=`<div class="eyebrow dark-eyebrow">${esc(g.level)} · ${esc(g.topic)} <span style="float:right;color:#9694aa">${placement}</span></div><h2>${esc(g.name)}</h2><p class="lesson-lead">${esc(g.lead)}</p><div class="formula"><b>La forme</b>${esc(g.form)}</div><div class="time-visual" aria-label="Repère visuel dans le temps"><span>AVANT</span><i></i><b>${marker}</b><i></i><span>APRÈS</span></div><h3>Quand l’utiliser ?</h3><ul class="use-list">${g.uses.map(x=>`<li>${esc(x)}</li>`).join("")}</ul><h3>Exemples</h3>${g.examples.map(x=>`<div class="example-line"><b>${esc(x[0])}</b><br>${esc(x[1])}</div>`).join("")}<div class="memory-tip"><strong>🧠 Image mentale</strong><br>${esc(g.memory)}<br><strong>À surveiller :</strong> ${esc(g.trap)}</div><button class="${done?"soft-button":"remember-button"}" id="lessonUnderstood" style="margin-top:13px">${done?"✓ Leçon vue":"J’ai compris cette leçon"}</button>`;}

function initVerbControls(){const s=$("#verbGroup");s.innerHTML='<option value="all">Toutes les familles</option>'+verbGroups.map(g=>`<option value="${g.id}">${esc(g.title)}</option>`).join("");s.addEventListener("change",renderVerbs);$("#verbSearch").addEventListener("input",renderVerbs);$("#verbRows").addEventListener("click",e=>{const b=e.target.closest("[data-verb-action]");if(!b)return;const v=verbs.find(x=>x.base===b.dataset.verb);if(state.knownVerbs.includes(v.base))state.knownVerbs=state.knownVerbs.filter(x=>x!==v.base);else state.knownVerbs.push(v.base);persist();renderVerbs();updateProgress()})}
function renderVerbs(){const term=$("#verbSearch").value.trim().toLowerCase(),group=$("#verbGroup").value,known=ids(state.knownVerbs),seen=new Set();const items=verbs.filter(v=>(group==="all"||v.group===group)&&(!term||`${v.base} ${v.past} ${v.part} ${v.fr}`.toLowerCase().includes(term))).filter(v=>{const k=`${v.base}-${v.past}-${v.part}`;if(seen.has(k))return false;seen.add(k);return true});$("#verbRows").innerHTML=items.length?items.map(v=>`<tr><td>${esc(v.base)}</td><td>${esc(v.past)}</td><td>${esc(v.part)}</td><td>${esc(v.fr)}</td><td><button class="verb-known ${known.has(v.base)?"done":""}" data-verb-action="know" data-verb="${esc(v.base)}">${known.has(v.base)?"Retenu ✓":"À revoir"}</button></td></tr>`).join(""):'<tr><td colspan="5" class="empty-state">Aucun verbe trouvé.</td></tr>';$("#verbCount").textContent=`${items.length} formes affichées · ${known.size} marquées comme retenues`}

let phraseTopic="all",phraseQuery="";
function initPhraseControls(){const s=$("#phraseTopic");const cats=[...new Map(phrases.map(p=>[p.topic,p.topicName])).entries()];s.innerHTML='<option value="all">Toutes les situations</option>'+cats.map(([id,t])=>`<option value="${id}">${esc(t)}</option>`).join("");s.addEventListener("change",()=>{phraseTopic=s.value;renderPhrases()});$("#phraseSearch").addEventListener("input",e=>{phraseQuery=e.target.value.toLowerCase().trim();renderPhrases()});$("#phraseGrid").addEventListener("click",e=>{const b=e.target.closest("[data-phrase-action]");if(!b)return;const p=phrases.find(x=>x.id===b.dataset.phrase);if(state.savedPhrases.includes(p.id))state.savedPhrases=state.savedPhrases.filter(x=>x!==p.id);else state.savedPhrases.push(p.id);persist();renderPhrases()})}
const phrases=phraseGroups.flatMap(g=>g.items.map(p=>({id:(g.id+"-"+p[0]).toLowerCase().replace(/[^a-z0-9]+/g,"-"),topic:g.id,topicName:g.title,en:p[0],fr:p[1],context:p[2]})));
function renderPhrases(){const saved=ids(state.savedPhrases),items=phrases.filter(p=>(phraseTopic==="all"||p.topic===phraseTopic)&&(!phraseQuery||`${p.en} ${p.fr} ${p.context}`.toLowerCase().includes(phraseQuery)));$("#phraseGrid").innerHTML=items.length?items.map(p=>`<article class="phrase-card"><div class="phrase-tools"><button class="${saved.has(p.id)?"saved":""}" data-phrase-action="save" data-phrase="${p.id}" aria-label="${saved.has(p.id)?"Retirer des":"Ajouter aux"} favoris">${saved.has(p.id)?"♥":"♡"}</button></div><h3>${esc(p.en)}</h3><p>${esc(p.fr)}</p><div class="context">${esc(p.context)}</div></article>`).join(""):'<div class="panel empty-state">Aucune phrase trouvée.</div>'}

function renderSounds(){$("#soundGrid").innerHTML=sounds.map(s=>`<article class="sound-card"><div class="sound-top"><span class="sound-symbol">${esc(s.symbol)}</span><h3>${esc(s.title)}</h3></div><p>${esc(s.text)}</p><div class="sound-examples">${esc(s.examples)}</div><p><b>Essaie :</b> ${esc(s.hint)}</p></article>`).join("")}

const grammarQuestions=[
  {q:"Complète : She ___ to school every day.",a:"walks",opts:["walks","is walk","walk","walking"],why:"Au présent simple, he / she / it prend souvent -s : She walks."},
  {q:"Complète : We ___ dinner when the phone rang.",a:"were having",opts:["were having","have had","had","are having"],why:"L’action était en cours et le téléphone l’a interrompue : past continuous + past simple."},
  {q:"Tu vois de gros nuages. Complète : It ___ rain.",a:"is going to",opts:["is going to","will have","would","has"],why:"Going to exprime ici une prédiction fondée sur un indice présent."},
  {q:"Complète : If I had more time, I ___ learn Italian.",a:"would",opts:["would","will","did","have"],why:"Hypothèse imaginaire : if + past simple, puis would + verbe."},
  {q:"Quelle phrase parle d’une expérience sans préciser quand ?",a:"I’ve been to Canada.",opts:["I’ve been to Canada.","I went to Canada in 2022.","I go to Canada every year.","I was going to Canada."],why:"Une expérience jusqu’à maintenant se dit souvent au present perfect."},
  {q:"Après ‘Did you…’, quelle forme du verbe utilise-t-on ?",a:"La base verbale",opts:["La base verbale","Le prétérit","Le participe passé","La forme en -ing"],why:"Did porte déjà la marque du passé : Did you go?"},
  {q:"‘If you heat ice, it melts’ exprime…",a:"Une règle générale",opts:["Une règle générale","Un regret passé","Un plan futur","Une action en cours"],why:"Le conditionnel zéro relie deux présents pour une vérité générale."},
  {q:"Complète : I ___ my keys. I can’t get in.",a:"have lost",opts:["have lost","lost yesterday","am losing yesterday","had lose"],why:"La perte passée a un résultat maintenant : impossible d’entrer."},
  {q:"Quel modal donne surtout un conseil ?",a:"should",opts:["should","mustn’t","might","can’t"],why:"Should sert souvent à conseiller : You should rest."},
  {q:"Complète : The train ___ at 7:30 tomorrow.",a:"leaves",opts:["leaves","will leaves","is leave","leave"],why:"Le présent simple sert pour les horaires officiels, même futurs."}
];
let quizQuestions=[],quizIndex=0,quizScore=0,quizLocked=false;
function shuffle(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
function distinct(values){const seen=new Set();return values.map(value=>String(value??"").trim()).filter(value=>{const key=value.toLocaleLowerCase();if(!key||seen.has(key))return false;seen.add(key);return true})}
function verbForms(value){return distinct(String(value??"").split("/"))}
function makeQuizOptions(correctForms,distractors){
  const answers=distinct(correctForms);
  if(!answers.length)throw new Error("Une question du quiz n’a aucune bonne réponse.");
  const accepted=new Set(answers.map(value=>value.toLocaleLowerCase()));
  const options=[answers[Math.floor(Math.random()*answers.length)]];
  for(const value of shuffle(distractors)){
    const option=String(value??"").trim(),key=option.toLocaleLowerCase();
    if(!key||accepted.has(key)||options.some(item=>item.toLocaleLowerCase()===key))continue;
    options.push(option);
    if(options.length===4)break;
  }
  for(const fallback of ["Je ne sais pas","À revoir","Je passe"]){
    if(options.length===4)break;
    if(!options.some(item=>item.toLocaleLowerCase()===fallback.toLocaleLowerCase()))options.push(fallback);
  }
  return shuffle(options);
}
function makeQuiz(){
  const questions=[];
  for(const word of shuffle(words).slice(0,3))questions.push({
    kind:"Vocabulaire",q:`Comment dit-on « ${word.fr} » en anglais ?`,a:word.en,
    opts:makeQuizOptions([word.en],words.filter(item=>item.id!==word.id).map(item=>item.en)),
    why:`${word.en} signifie « ${word.fr} ». Exemple : ${word.example}`
  });
  const uniqueQuizVerbs=[...new Map(verbs.map(verb=>[verb.base.toLowerCase(),verb])).values()];
  for(const verb of shuffle(uniqueQuizVerbs).slice(0,3)){
    const answers=verbForms(verb.past);
    questions.push({
      kind:"Verbes",q:`Quel est le prétérit de ‘${verb.base}’ (${verb.fr}) ?`,a:answers[0],answers,
      opts:makeQuizOptions(answers,verbs.filter(item=>item.base!==verb.base).flatMap(item=>verbForms(item.past))),
      why:`Les formes de ${verb.base} sont ${verb.base} – ${verb.past} – ${verb.part}.`
    });
  }
  for(const question of shuffle(grammarQuestions).slice(0,4))questions.push({kind:"Grammaire",...question});
  return shuffle(questions);
}
function startQuiz(){quizQuestions=makeQuiz();quizIndex=0;quizScore=0;quizLocked=false;renderQuizQuestion()}
function renderQuiz(){
  const best=state.bestScore;
  $("#bestScore").textContent=best===null?"Meilleur score : —":`Meilleur score : ${best} / 10`;
  if(!quizQuestions.length)$("#quizBox").innerHTML=`<div class="quiz-start"><div class="quiz-big">🎯</div><h2>Dix petites questions</h2><p>Des mots, des verbes et de la grammaire. Si tu hésites, tente une réponse : l’explication t’aidera à retenir.</p><button class="start-quiz" id="startQuiz">Lancer le défi →</button></div>`;
}
function renderQuizQuestion(){
  const question=quizQuestions[quizIndex];
  if(!question){quizQuestions=[];renderQuiz();return}
  $("#quizBox").innerHTML=`<div class="quiz-progress"><span>${esc(question.kind)}</span><b>Question ${quizIndex+1} / ${quizQuestions.length}</b></div><div class="quiz-bar"><i style="width:${(quizIndex/quizQuestions.length)*100}%"></i></div><h2 class="quiz-question">${esc(question.q)}</h2><div class="quiz-options">${question.opts.map((option,index)=>`<button type="button" data-answer="${index}">${esc(option)}</button>`).join("")}</div><div class="quiz-feedback" id="quizFeedback" aria-live="polite">Choisis une réponse.</div><div class="quiz-next"><button type="button" id="nextQuiz" disabled>${quizIndex===quizQuestions.length-1?"Voir mon résultat":"Continuer →"}</button></div>`;
}
$("#quizBox").addEventListener("click",event=>{
  if(event.target.closest("#startQuiz")){startQuiz();return}
  if(event.target.closest("#nextQuiz")){
    if(!quizLocked)return;
    quizIndex++;
    if(quizIndex>=quizQuestions.length){
      const total=quizQuestions.length;
      if(state.bestScore===null||quizScore>state.bestScore)state.bestScore=quizScore;
      persist();
      quizQuestions=[];
      renderQuiz();
      const percentage=Math.round(quizScore/total*100);
      $("#quizBox").innerHTML=`<div class="quiz-finish"><div class="quiz-big">${percentage>=80?"🌟":percentage>=50?"👏":"🌱"}</div><h2>${quizScore} bonne${quizScore>1?"s":""} réponse${quizScore>1?"s":""} sur ${total}</h2><p>${percentage>=80?"Belle maîtrise ! Reviens plus tard pour ancrer les automatismes.":percentage>=50?"Tu avances bien. Relis les explications et tente un nouveau tour.":"Chaque erreur te montre quoi revoir. Recommence quand tu veux, les questions changent."}</p><button class="start-quiz" id="startQuiz">Rejouer avec d’autres questions →</button></div>`;
      $("#bestScore").textContent=`Meilleur score : ${state.bestScore} / 10`;
    }else{quizLocked=false;renderQuizQuestion()}
    return;
  }
  const button=event.target.closest("[data-answer]");
  if(!button||quizLocked)return;
  const question=quizQuestions[quizIndex],answerIndex=Number(button.dataset.answer);
  if(!Number.isInteger(answerIndex)||answerIndex<0||answerIndex>=question.opts.length)return;
  const answer=question.opts[answerIndex],validAnswers=question.answers||[question.a];
  const isCorrect=validAnswers.some(value=>String(value).toLocaleLowerCase()===answer.toLocaleLowerCase());
  quizLocked=true;
  if(isCorrect)quizScore++;
  $("#quizBox [data-answer]")&&$$('#quizBox [data-answer]').forEach(option=>{
    option.disabled=true;
    if(validAnswers.some(value=>String(value).toLocaleLowerCase()===option.textContent.toLocaleLowerCase()))option.classList.add("correct");
  });
  if(!isCorrect)button.classList.add("wrong");
  const feedback=$("#quizFeedback");
  feedback.classList.add(isCorrect?"good":"bad");
  feedback.innerHTML=`<b>${isCorrect?"Bien joué !":"On corrige :"}</b> ${esc(question.why)}`;
  $("#nextQuiz").disabled=false;
});
function updateProgress(){const total=grammar.length,seen=state.seenLessons.length,known=state.knownWords.length;$("#progressText").textContent=`${seen} / ${total}`;$("#knownText").textContent=`${known} mot${known===1?"":"s"}`;$("#progressBar").style.width=`${Math.min(100,seen/total*100)}%`;$("#progressMood").textContent=seen===0?"À toi de jouer":seen<5?"Bon départ !":seen<12?"Tu avances bien":"Belle régularité !";}
function updateStreak(){const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;const now=new Date(),today=dateKey(now);if(state.lastVisit!==today){const y=new Date(now);y.setDate(y.getDate()-1);state.streak=state.lastVisit===dateKey(y)?Math.max(1,state.streak+1):1;state.lastVisit=today;persist()}$("#streak").textContent=`${state.streak||1} jour${(state.streak||1)>1?"s":""} de suite`}

function applyPreferences(){document.documentElement.dataset.theme=state.theme;document.documentElement.dataset.reduceMotion=String(state.reduceMotion);const color={clair:"#f8f7f2",lavande:"#f4f0ff",ocean:"#f0f8fa",nuit:"#171725"}[state.theme];$("#themeColor").content=color;}
function renderSettings(){
  $("#themeSelect").value=state.theme;
  $("#reduceMotion").checked=state.reduceMotion;
  $$('[name="study-day"]').forEach(input=>input.checked=state.studyDays.includes(Number(input.value)));
  const today=new Date().getDay(),selected=state.studyDays.map(day=>studyDayLabels.find(([id])=>id===day)?.[1]).filter(Boolean);
  $("#studyDaySummary").textContent=selected.length?"Tes jours : "+selected.join(", ")+". "+(state.studyDays.includes(today)?"Aujourd’hui est un jour choisi.":"Aujourd’hui est un jour libre."):"Choisis au moins un jour.";
}
function initSettings(){
  $("#themeSelect").addEventListener("change",event=>{state.theme=themes.includes(event.target.value)?event.target.value:"clair";applyPreferences();persist();});
  $("#reduceMotion").addEventListener("change",event=>{state.reduceMotion=event.target.checked;applyPreferences();persist();});
  $("#studyDays").addEventListener("change",event=>{if(!event.target.matches('[name="study-day"]'))return;const selected=$$('[name="study-day"]:checked').map(input=>Number(input.value));if(!selected.length){event.target.checked=true;toast("Garde au moins un jour choisi.");return;}state.studyDays=validStudyDays(selected);persist();renderSettings();});
  $("#resetSettings").addEventListener("click",()=>{state.theme="clair";state.studyDays=[1,2,3,4,5];state.reduceMotion=false;applyPreferences();persist();renderSettings();toast("Tes réglages sont revenus aux valeurs de départ.")});
  $("#exportProgress").addEventListener("click",()=>{const data={site:"Anglais sans délai",exportedAt:new Date().toISOString(),progress:{knownWords:state.knownWords,seenLessons:state.seenLessons,knownVerbs:state.knownVerbs,savedPhrases:state.savedPhrases,bestScore:state.bestScore,streak:state.streak},preferences:{theme:state.theme,studyDays:state.studyDays,reduceMotion:state.reduceMotion}};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const link=document.createElement("a");link.href=url;link.download="anglais-sans-delai-progres.json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast("Copie de tes progrès téléchargée.")});
  renderSettings();
}
function updateWordOfDay(){const w=words[new Date().getDate()%words.length];$("#wordOfDay").textContent=w.en;$("#wordOfDayFr").textContent=w.fr;$("#wordOfDayExample").textContent=w.example;$("#wordOfDayCount").textContent="À retenir"}
$("#resetProgress").addEventListener("click",()=>{if(confirm("Effacer les mots retenus, les leçons vues et le meilleur score sur cet appareil ?")){const preferences={theme:state.theme,studyDays:state.studyDays,reduceMotion:state.reduceMotion};state={...freshState(),...preferences};persist();updateStreak();updateProgress();renderWords();renderVerbs();renderPhrases();renderSettings();toast("Tes progrès ont été effacés.")}});
function init(){applyPreferences();initWordControls();initGrammarTopics();initVerbControls();initPhraseControls();initSettings();updateStreak();updateProgress();updateWordOfDay();renderWords();renderGrammar();renderVerbs();renderPhrases();renderSounds();renderQuiz();const hash=location.hash.slice(1);if(viewNames[hash])show(hash);if("serviceWorker"in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("./sw.js").catch(()=>{})}
init();
